apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-app
  namespace: cicd-demo
  labels:
    app: cicd-demo-app
spec:
  type: ClusterIP
  selector:
    app: cicd-demo-app
  ports:
    - name: http
      port: 80
      targetPort: http
